package com.yvan.gestiondestock.exception;

public enum ErrorCode {

  ARTICLE_NOT_FOUND(1000),
  ARTICLE_NOT_VALID(1001),
  CATEGORY_NOT_FOUND(2000),
  CATEGORY_NOT_VALID(2001),
  CLIENT_NOT_FOUND(3000),
  CLIENT_NOT_VALID(3001),

  //TODO complete the rest of the code
  COMMANDE_CLIENT_NOT_FOUND(4000),
  COMMANDE_CLIENT_NOT_VALID(4001),
  COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
    ENTREPRISE_NOT_FOUND(6000),
  FOURNISSSEUR_CLIENT_NOT_FOUND(7000),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(8000),
  LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(9000),
  LIGNE_VENTE_NOT_FOUND(10000),
  MVT_STK_NOT_FOUND(11000),
  UTILISATEUR_NOT_FOUND(12000),
  VENTE_NOT_FOUND(13000),
  VENTE_NOT_VALID(14000),
  ;


  private int code;

  ErrorCode(int code){

    this.code = code;
  }

  public int getCode(){
    return code;
  }

}
